// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class Feedback : MonoBehaviour {
	
	private CardboardHead head;
	private float lastScale;

	void Start() {
		reset ();
		lastScale = 0.0f;
		head = Camera.main.GetComponent<StereoController>().Head;
	}
	
	void Update() {
		if (transform.localScale.y - 0.00015f < lastScale) {
			reset();
		}
		lastScale = transform.localScale.y;
	}

	/**
	 * 
	 */
	public void looking() {
		scaleY(0.05f);
	}

	/**
	 * 
	 */
	public void reset() {
		Vector3 scale = transform.localScale;
		scale.y = 0.0f;
		transform.localScale = scale;
	}

	/**
	 * 
	 */
	public void scaleY(float f) {
		Vector3 scale = transform.localScale;
		scale.y = transform.localScale.y + f;
		transform.localScale = scale;
	}
	
}
