// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Intro : MonoBehaviour {
	
	private CardboardHead head;
	private float delay;
	
	void Start() {
		delay = 0.0f;
		head = Camera.main.GetComponent<StereoController>().Head;
		if (Toolbox.Instance.mode == Constants.VR_MODE) {
			Cardboard.SDK.VRModeEnabled = true;
		} else {
			Cardboard.SDK.VRModeEnabled = false;
		}
		try {
			GetComponentInChildren<Cardboard> ().DevicePause (false);
		} catch {
		}
	}
	
	void Update() {
		RaycastHit hit;
		bool isLookedAt = GetComponent<Collider>().Raycast(head.Gaze, out hit, Mathf.Infinity);
		if (!isLookedAt) {
			delay = Time.time + 1.5f;
		} else {
			head.BroadcastMessage("looking");
		}
		if (isLookedAt && Time.time>delay) { 
			Application.LoadLevel(Constants.INTRO_SCENE);
			delay = Time.time + 1.5f;
		}
	}
}